package org.imzdong.study.springbootmybatis.model;

public class HealthTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_task.record_id
     *
     * @mbg.generated
     */
    private Integer record_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_task.user_id
     *
     * @mbg.generated
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_task.task_name
     *
     * @mbg.generated
     */
    private String task_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_task.id
     *
     * @return the value of health_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_task.id
     *
     * @param id the value for health_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_task.record_id
     *
     * @return the value of health_task.record_id
     *
     * @mbg.generated
     */
    public Integer getRecord_id() {
        return record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_task.record_id
     *
     * @param record_id the value for health_task.record_id
     *
     * @mbg.generated
     */
    public void setRecord_id(Integer record_id) {
        this.record_id = record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_task.user_id
     *
     * @return the value of health_task.user_id
     *
     * @mbg.generated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_task.user_id
     *
     * @param user_id the value for health_task.user_id
     *
     * @mbg.generated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_task.task_name
     *
     * @return the value of health_task.task_name
     *
     * @mbg.generated
     */
    public String getTask_name() {
        return task_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_task.task_name
     *
     * @param task_name the value for health_task.task_name
     *
     * @mbg.generated
     */
    public void setTask_name(String task_name) {
        this.task_name = task_name == null ? null : task_name.trim();
    }
}