package org.imzdong.study.mybatis.generator.dao;

import java.util.List;
import org.imzdong.study.mybatis.generator.model.HealthRecord;

public interface HealthRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_record
     *
     * @mbg.generated
     */
    int insert(HealthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_record
     *
     * @mbg.generated
     */
    HealthRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_record
     *
     * @mbg.generated
     */
    List<HealthRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HealthRecord record);
}