package org.imzdong.study.springbootmybatis.dao;

import org.imzdong.study.springbootmybatis.model.HealthTask;

import java.util.List;

public interface HealthTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_task
     *
     * @mbg.generated
     */
    int insert(HealthTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_task
     *
     * @mbg.generated
     */
    HealthTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_task
     *
     * @mbg.generated
     */
    List<HealthTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HealthTask record);
}